---
abstract: 'Parse OpenGL Shader Language files into an abstract syntax tree'
author:
  - 'Tom Molesworth <tom@entitymodel.com>'
build_requires:
  Test::Deep: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-GLSL
requires:
  Parser::MGC: 0.09
  parent: 0
version: 0.001
